### PR TITLE
Add logpush param

### PR DESCRIPTION
**Pull request by myakhnis-shopify**
## Description

- Adds logpush support based on `https://github.com/cloudflare/cloudflare-go/pull/1160` (but adapted to work with older APIs)

## Has your change been tested?

Tested internally

## Types of changes

What sort of change does your code introduce/modify?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

**Comment by sbfaulkner** [comment]
fwiw I think this is already upstream ... we're trying to figure out the best way to get back in sync or rebase with upstream since some of the most recent upstream changes have made rebasing more difficult than the last time(s)

**Comment by myakhnis-shopify** [comment]
Yeah, I based my change partially off of theirs. But it looks like they refactored some of `workers.go` so we'll probably have to manually review/reapply changes whenever we want to do that.

**Comment by sbfaulkner** [comment]
@myakhnis-shopify 
yeah... I'm looking at that now because we need the upstream changes for the terraform provider :-/

**Comment by sbfaulkner** [comment]
as per slack DM...
* we (assets/traffic/prodeng) no longer need a fork of the terraform provider, which means we no longer need a fork of cloudflare-go
* the upstream changes are not compatible with the current local changes

for reference the list of PRs that are included in the local branch...

* Shopify/cloudflare-go#13 -- equivalent upstreamed in cloudflare/cloudflare-go#1177
* Shopify/cloudflare-go#17 -- unable to upstream due to undocumented api
* Shopify/cloudflare-go#18 -- unable to upstream due to undocumented api
* Shopify/cloudflare-go#16 -- unable to upstream due to undocumented api
* Shopify/cloudflare-go#23 -- unable to upstream due to undocumented api 
* Shopify/cloudflare-go#42 -- equivalent upstreamed in cloudflare/cloudflare-go#1149
* Shopify/cloudflare-go#44 -- unlikely to upstream since it's a change in api?
* Shopify/cloudflare-go#65 -- unable to upstream due to undocumented api 
* Shopify/cloudflare-go#90 -- this PR... already upstream in cloudflare/cloudflare-go#1160

most (if not all) of these likely become unneeded once Workers for Platforms is adopted

My suggestion is to disconnect the fork and rename this repo for oxygen-specific "legacy" usage, so that if/when we need to fork the official master again we can.

**Comment by myakhnis-shopify** [comment]
> My suggestion is to disconnect the fork and rename this repo for oxygen-specific "legacy" usage

I chatted with the team, and we agree it's reasonable. That being said, this change will likely still be merged, and I'll file a separate ticket for the rename.

**Review by uri — APPROVED** [review]
Checked against upstream looks good.

**Pull request merged**
